def a_syn_error
  x = 1
end 

return a_syn_error